M3L1. Создать экран "Открыть документ"
Select-IOS-Team/MdEditor pull request #11
Opened 2023-04-19 16:50 UTC by EvgeniMeleshin

# Что было сделано?

- создана сцена открытия документов с начальным заполнением из подготовленных файлов.
- добавлен enum для определения источника для перехода на другой экран. 
- добавлен роутинг для сцены документов (навигации по папкам пока нет)

2023-04-21 06:48 UTC, Blissfulman requested changes

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	}
Это всё нужно было при вёрстке фреймами. А сейчас незачем.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		label.textColor = Constants.additionalTextColor
Это дополнительный цвет (тёмно-серый). Использовался для дополнительный данных. Тут он вряд ли нужен. Чёрный цвет по умолчанию будет норм.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		imageView.isUserInteractionEnabled = true
Здесь не нужно взаимодействие с картинкой. Раньше это нужно было, чтобы чекбокс мог обрабатывать касания.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	var completionCheckboxTapAction: (() -> Void)?
Не используется

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		contentView.addGestureRecognizer(tapGestureRecognizer)
А для чего это? Мы же можем обрабатывать выбор ячейки через делегата таблицы.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	}
Лишнее, если не используется

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		}
Давай для единообразия и лаконичности писать краткую форму замыканий без указания имени параметра и, тем более, без возвращаемого `Void`. Используя `$0`.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +	var fileExtension: String = ""
По стайлгайду тип явно указывать не стоит если он выводится сам из контекста

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +		}
Было бы хорошо добавить обработку ошибок

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentAssembly.swift
> +		let convertToResponseWorker: IOpenDocumentWorker = OpenDocumentWorker()
Здесь нет необходимости указывать протоколы. Они ни на что не влияют.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	private let fileExplorerWorker: IFileExplorerWorker?
Для чего им быть опционалами?

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	// swiftlint: enable line_length
Зачем здесь отключать правило, ведь оно именно для того и нужно, чтобы не писать длинные строки?

Отключаем мы иногда в каких-то специфических местах вроде генерируемых файлах или тестах. Там строгость соблюдения правил может быть ниже. Но в продакшн коде их надо стараться соблюдать. Здесь просто нужно было сделать перенос параметров.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	// MARK: - Internal Methods
// MARK: - IFileExplorerWorker

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentPresenter.swift
> +	// MARK: - Internal Methods
// MARK: - IOpenDocumentPresenter

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +enum MenuItemsOpenDocumentsScene {
Имя неудачное. Файлы и папки - это всё-таки не элементы меню. Тут больше подойдёт что-то вроде `DirectoryObject` или `DirectoryObjectType`.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +class OpenDocumentViewController: UIViewController {
final

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentPresenter.swift
> +class OpenDocumentPresenter: IOpenDocumentPresenter {
final

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +	let interactor: IOpenDocumentInteractor?
Опционал не нужен

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.scrollsToTop = true
Для чего тут скроллинг вверх?

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.deselectRow(at: indexPath, animated: true)
Для чего тут деселект? В ячейке уже установлен `selectionStyle = .none`.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		self.router.routeToViewController(menuItem: model.menuItem, root: model.fullName, title: model.name)
`self` лишний

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +			make.height.equalToSuperview()
Указан размер таблицы, но не зафиксировано её положение. Она может куда-то уплыть в сторону, сохраняя свой размер. Надо прибивать её к границам родительской вью, а размер вычислится автоматом.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +class OpenDocumentWorker: IOpenDocumentWorker {
final

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +	// MARK: - Internal Methods
// MARK: - IOpenDocumentWorker

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +}
Назван как `File`, но при этом есть свойство `fileIsDir`. Стоит подобрать какое-то имя, чтобы не вводить в заблуждение что это за объект. Абстракция плохая получается.

Точно все свойства должны быть переменными? Сейчас получается, что файл может превратиться в папку и наоборот.

Точно нужно, чтобы это был класс?

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +}
Если это файл менеджер, то и назвать его лучше `FIleManager`. Воркеры - это обобщённое название всех вспомогательных объектов, которые оперируют логикой внутри сцены, помощники для интерактора. Но это не значит что их всех надо называть используя слово `Worker`. Если название может дать понять роль объекта, то так его лучше и называть, это улучшает читаемость. `Factory`, `Adaptor`, `Manager`, `Helper` и т.д.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +}
Если их у сцены несколько, то можно их положить в папку "Workers", проще будет навигация по файлам.

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +class FileExplorerWorker: IFileExplorerWorker {
final

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/StartSceneRouter.swift
>  }
Почему это здесь, а не в `StartSceneModel`?

2023-04-21 06:48 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/StartSceneModel.swift
> +			let menuItem: MenuItemsStartScene
Зачем каждому элементу меню знать о всех элементах? Достаточно передать ему его тип.

Если б сделал этот тип вложенным внутрь неймспейса сцены, то и название такое длинное не нужно было бы. Ещё имя типа должно быть в единственном числе.

2023-04-21 07:11 UTC, Blissfulman requested changes

2023-04-21 07:11 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +	}
А это точно в `viewWillAppear` нужно разместить? В `viewDidLoad` не достаточно?

2023-04-21 07:11 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +	func prepareViewModel(data: [File]) -> [OpenDocumentModel.OpenDocumentViewData.FileViewModel]
Док. коммент бы добавить

2023-04-21 07:11 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.snp.makeConstraints { make -> Void in
По аналогии с другими файлами лазают стоит вынести в метод `setupLayout()`

2023-04-21 07:31 UTC, Blissfulman requested changes

2023-04-21 07:31 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			guard let openDocumentViewController = viewController as? OpenDocumentViewController else { return }
Для чего здесь кастинг именно до `OpenDocumentViewController`? Далее нигде не вижу необходимости именно в этом типе.

2023-04-21 07:31 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			let destinationViewController = openDocumentViewController as UIViewController
А этот кастинг для чего? `openDocumentViewController` и так уже является `UIViewController`.

2023-04-21 13:46 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	}
fix

2023-04-21 13:46 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		label.textColor = Constants.additionalTextColor
fix

2023-04-21 13:46 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		imageView.isUserInteractionEnabled = true
fix

2023-04-21 13:46 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	var completionCheckboxTapAction: (() -> Void)?
fix

2023-04-21 13:47 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		contentView.addGestureRecognizer(tapGestureRecognizer)
fix

2023-04-21 13:47 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +	}
fix

2023-04-21 13:47 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/Cells/FileTableViewCell.swift
> +		}
fix

2023-04-21 13:48 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +	var fileExtension: String = ""
fix

2023-04-21 13:48 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentAssembly.swift
> +		let convertToResponseWorker: IOpenDocumentWorker = OpenDocumentWorker()
fix

2023-04-21 13:48 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	private let fileExplorerWorker: IFileExplorerWorker?
fix

2023-04-21 13:48 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	// swiftlint: enable line_length
fix

2023-04-21 13:48 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +	// MARK: - Internal Methods
fix

2023-04-21 13:49 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentPresenter.swift
> +	// MARK: - Internal Methods
fix

2023-04-21 13:49 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +enum MenuItemsOpenDocumentsScene {
fix

2023-04-21 13:50 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +class OpenDocumentViewController: UIViewController {
fix

2023-04-21 13:50 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentPresenter.swift
> +class OpenDocumentPresenter: IOpenDocumentPresenter {
fix

2023-04-21 13:51 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +	let interactor: IOpenDocumentInteractor?
fix

2023-04-21 13:52 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.scrollsToTop = true
fix

2023-04-21 13:52 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.deselectRow(at: indexPath, animated: true)
fix

2023-04-21 13:52 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		self.router.routeToViewController(menuItem: model.menuItem, root: model.fullName, title: model.name)
fix

2023-04-21 13:53 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +			make.height.equalToSuperview()
Это поправил но с констрейнтами еще не до конца

2023-04-21 13:53 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +class OpenDocumentWorker: IOpenDocumentWorker {
fix

2023-04-21 13:53 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +	// MARK: - Internal Methods
fix

2023-04-21 13:53 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +}
fix

2023-04-21 13:55 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +}
fix. Скорее всего этот менеджер будет на несколько сцен

2023-04-21 13:55 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +class FileExplorerWorker: IFileExplorerWorker {
fix

2023-04-21 13:55 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/StartScene/StartSceneRouter.swift
>  }
fix

2023-04-21 13:56 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +	}
fix

2023-04-21 13:56 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentWorker.swift
> +	func prepareViewModel(data: [File]) -> [OpenDocumentModel.OpenDocumentViewData.FileViewModel]
fix

2023-04-21 13:56 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		tableView.snp.makeConstraints { make -> Void in
fix

2023-04-21 13:57 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			guard let openDocumentViewController = viewController as? OpenDocumentViewController else { return }
Там потому что viewController с типом протокола вроде

2023-04-21 13:58 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			let destinationViewController = openDocumentViewController as UIViewController
Это хотел сначала какой-то универсальный роутер сделать, потом забыл убрать

2023-04-21 13:58 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			let destinationViewController = openDocumentViewController as UIViewController
fix

2023-04-21 16:05 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			guard let openDocumentViewController = viewController as? OpenDocumentViewController else { return }
Думаю, что можно `IOpenDocumentViewController` подписать под `UIViewController`, он всё равно должен реализовываться вью контроллером. И тогда этот кастинг не потребуется.

А ещё видел много где, что в роутерах хранимое свойство делают `weak var viewController: UIViewController?` (не протоколом). Тогда тоже кастинг не нужен будет. Потому что роутеру по сути не нужно знать, что вью контроллер соответствует протоколу, ведь он не должен общаться с вью посредством методов этого протокола.

Щас глянул, у меня на рабочем проекте второй вариант используется.

2023-04-21 16:09 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		)
Как-то это в этом методе смотрится не очень на фоне вызова других методов. Лучше вынести в `configureUI()`

2023-04-21 16:14 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		router.dataStore = OpenDocumentRoutingDTO(title: model.title, currentPath: model.fullName)
А вот то, что вью управляет `dataStore` в роутере - точно плохо. Она вообще ничего не должна знать про внутреннее устройство роутера, кроме его публичных методов. Этот DTO просто в параметре метода передать надо. Дальше роутер сам с ним разберётся.

2023-04-21 16:28 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +	var objects: [DirectoryObject] = []
А для чего этот массив хранить внутри менеджера и почему оно не приватное?

2023-04-21 16:31 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +		let fileManager = FileManager.default
Для того, чтобы можно было тестировать и подменять этот менеджер его надо сделать зависимостью. Можно хотя бы внутри инициализатора ему значение по умолчанию передать, если не передавать снаружи.

2023-04-21 16:37 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +class OpenDocumentInteractor: IOpenDocumentInteractor {
final

2023-04-23 05:40 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentInteractor.swift
> +class OpenDocumentInteractor: IOpenDocumentInteractor {
fix

2023-04-23 05:43 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +		let fileManager = FileManager.default
По этому моменту не понял, он в ассембли интерактору устанавливается через инит инъекцию, надо еще как то?

2023-04-23 05:44 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +		}
fix пока localizeDescription

2023-04-23 05:45 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentRouter.swift
> +			guard let openDocumentViewController = viewController as? OpenDocumentViewController else { return }
fix

2023-04-23 05:45 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		)
fix

2023-04-23 05:46 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +	var objects: [DirectoryObject] = []
По идее его можно убрать, и в методе создавать. Но пока я просто private сделал

2023-04-23 06:49 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/Cells/MenuItemTableViewCell.swift
> +	}
В этой анимации есть минус. Когда долго держишь палец на ячейке, ничего не происходит, а в момент окончания касания она начинается. Смотрится это не очень.

Логичней было бы при удержание пальца проигрывать первую часть анимации, а при опускании - вторую.

2023-04-23 06:52 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/StartSceneViewController.swift
> +		}
Такой подход не очень хороший, когда анимация ячейки в одном месте, а задержка для того, чтобы анимацию успеть увидеть - в другом. Получается несогласованность. Если в одном месте настройки изменятся, то в другом легко забыть их не поменять для соответствия. Если не знаешь этого, то вообще не понятно, что это всё как-то связано.

2023-04-23 07:28 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/StartSceneViewController.swift
> +		}
Оставь пока так. У меня есть универсальная реализация такой анимации для любых вьюшек. Я потом сам заменю.

2023-04-23 07:28 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/StartScene/Cells/MenuItemTableViewCell.swift
> +	}
Оставь пока так. У меня есть универсальная реализация такой анимации для любых вьюшек. Я потом сам заменю.

2023-04-23 07:42 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +		let fileManager = FileManager.default
Можно в ассембли создать и передать, а можно в инициализатор значением по умолчанию создать.

2023-04-23 07:54 UTC, Blissfulman commented on MdEditor/Presentation/Common/Managers/FileExplorerManager.swift
> +	private var objects: [DirectoryObject] = []
Коммент не поправил. А для чего ты его всё-таки оставил снаружи метода?

2023-04-23 07:55 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerWorker.swift
> +		}
Ок, давай добавим обработку ошибок в отдельной задаче, чтобы эту побыстрее влить. Можешь резолвнуть.

2023-04-23 07:58 UTC, Blissfulman commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +			make.height.equalToSuperview()
А что ещё не до конца? Вроде уже всё ок.

2023-04-23 08:13 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +			make.height.equalToSuperview()
В самой ячейке еще предупреждения о констрейнтах вылетают

2023-04-23 08:13 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +		router.dataStore = OpenDocumentRoutingDTO(title: model.title, currentPath: model.fullName)
Это мы теперь убрали

2023-04-23 08:17 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/StartScene/Cells/MenuItemTableViewCell.swift
> +	}
Отлично, покажи потом как сделаешь

2023-04-23 08:21 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Common/Managers/FileExplorerManager.swift
> +	private var objects: [DirectoryObject] = []
У Кирилла просто было снаружи. Я тоже решил так оставить

2023-04-23 08:36 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/OpenDocumentViewController.swift
> +			make.height.equalToSuperview()
fix

2023-04-23 08:36 UTC, Blissfulman commented on MdEditor/Presentation/Common/Managers/FileExplorerManager.swift
> +	private var objects: [DirectoryObject] = []
Но он же говорил, что у него плохой код и не надо всё за ним повторять))

2023-04-23 08:37 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Scenes/OpenDocumentScene/FileExplorerManager.swift
> +		let fileManager = FileManager.default
fix

2023-04-23 08:37 UTC, EvgeniMeleshin commented on MdEditor/Presentation/Common/Managers/FileExplorerManager.swift
> +	private var objects: [DirectoryObject] = []
fix

2023-04-23 08:41 UTC, Blissfulman commented on MdEditor/Presentation/Common/Managers/FileExplorerManager.swift
> +	private var objects: [DirectoryObject] = []
Если переменная только внутри метода используется, то снаружи хранить её лишнее использование памяти , а также есть риск ошибиться и забыть обнулить её. Либо её начнут использовать не по назначению в других методах.

Ты её оставил снаружи, тебе понятно зачем она. А потом придут другие участники команды и решат что её как-то можно использовать, раз она есть. И всё это не понятно к чему может привести в будущем.

2023-04-23 08:43 UTC, Blissfulman approved these changes, later dismissed

2023-04-23 09:16 UTC, Blissfulman approved these changes

2023-04-23 09:18 UTC, merged