M4L1. Добавлен конвертер в PDF формат с использованием PDFKit
Select-IOS-Team/MdEditor pull request #33
Opened 2023-06-07 03:35 UTC by EgorSau

- Добавил конвертер в PDF;
- Добавил новую сцену для отображения PDF документов;
- Добавил кнопку печати на EditScene;
- Внес изменения в Parser и Visitor для корректного отображения PDF документа.

2023-06-07 06:08 UTC, EvgeniMeleshin approved these changes, later dismissed

2023-06-07 07:47 UTC, Blissfulman requested changes

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Common/Extensions/UIGraphicsPDFRendererContext+addAttributedText.swift
> +	// swiftlint:enable all
А что тут за правило надо было выключить?

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowseHTMLFlow/BrowseHTMLCoordinator.swift
> +	}
А для чего тут этот комментарий? Это же реализация метода протокола и документация к этому методу должна быть в протоколе, а не в его реализации. И она уже есть в протоколе.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowseHTMLFlow/BrowseHTMLCoordinator.swift
> +	}
Какую логику ты тут обеспечиваешь, реализовав этот протокол?

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +}
Для чего пустой комментарий в протоколе?

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +/// Координатор сцены просмотра pdf-файла.
Лучше написать в док. комментарии, что это координатор флоу, а не сцены. Пока что в этом флоу всего одна сцена, но вообще, как правило, координаторы создаются для набора сцен (флоу).  Возможно, в последствии добавится ещё какой-то алерт, например и это будет формально второй сценой внутри одного флоу.

Так, к слову, у нас уже несколько координаторов с единственной сценой в каждом. По идее это избыточно и можно было бы обойтись меньшим количеством координаторов.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	// MARK: Lifecycle
Где-то марки с дефисом, где-то без. Лучше везде делать одинаково (с дефисом).

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	/// Стартует сцену с просмотром pdf-документа.
Этот док. коммент избыточен. Метод уже задокументирован в протоколе.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	weak var finishDelegate: ICoordinatorFinishDelegate?
По стайлгайду выше стоит размещать публичные, затем интернал и в конце приватные свойства/методы.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFInteractor.swift
> +	/// Получает данные для отображения на вью.
Если метод задокументирован в протоколе, то в реализации повторная документация избыточна

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFInteractor.swift
> +	// MARK: - Methods
// MARK: - IBrowsePDFInteractor

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFModel.swift
> +	}
Это не запрос. Это ответ.
Вообще, таким объектам сложно подобрать описание)
И может быть даже не сильно нужно на практике, когда их роль весьма очевидна.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFPresenter.swift
> +	}
Тоже лишний коммент

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFPresenter.swift
> +	// MARK: - Methods
// MARK: - IBrowsePDFPresenter

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	}()
Можно одной строкой если нет никаких настроек у вью

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +// MARK: UI Setup
В проекте не приняты такие комменты. Лучше просто `// MARK: - Private methods` для этого экстеншена и объединить его со следующим экстеншеном.
Для каждого приватного метода делать отдельный экстеншн с маркирующим комментом как-то избыточно.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +}
Если экстеншн приватный, то метод делать приватным уже избыточно

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	// swiftlint:enable all
Для чего тут отключение всех правил?

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +	private func setupNavigation() {
Неудачное название метода. Очень абстрактное. Здесь добавляется кнопка печати. Так и стоит назвать метод.

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +// MARK: - Private methods - navigation setup
Просто `// MARK: - Private methods`

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +	func convert(text: String, pdfAuthor: String, pdfTitle: String) -> Data {
Прям бросаются в глаза дублирующие док. комменты)

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +	func convert(text: String, pdfAuthor: String, pdfTitle: String) -> Data {
Нет маркирующих комментов

2023-06-07 07:47 UTC, Blissfulman commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +				cursor += 24
Много магических чисел. Стоит вынести в приватный `enum Constants` внутри файла.

2023-06-07 08:27 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +/// Координатор сцены просмотра pdf-файла.
Хотя в принципе, если каждый флоу будет обрастать новыми сценами, но всё нормально с количеством координаторов.

2023-06-07 08:42 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowseHTMLFlow/BrowseHTMLCoordinator.swift
> +	}
Координаторы уже имеют реализацию этого метода по умолчанию. Здесь ты её переопределил для этого координатора. Сейчас у тебя получается, что при уведомлении о финише какого-то дочернего координатора ты финишируешь этот. Для чего это?

И при этом не высвобождаешь дочерний координатор, оставляя retain cycle.

Скорее всего, просто перепутал назначение этого протокола и метода.

2023-06-07 09:21 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFModel.swift
> +	}
Для чего в моделях `let text: String` если он нигде не используется?

2023-06-07 09:23 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +		pdfView.pageBreakMargins = UIEdgeInsets(top: 32, left: 16, bottom: 16, right: 16)
Стоит вынести в константы (как одно свойство типа `UIEdgeInsets`)

2023-06-07 09:25 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +		pdfView.pageBreakMargins = UIEdgeInsets(top: 32, left: 16, bottom: 16, right: 16)
Эти две строки как раз относятся к настройке вью и их логичнее было бы разместить внутри замыкания, создающего этот `pdfView`.
А здесь уже только данные передавать.

2023-06-07 09:29 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneInteractor.swift
> +	func showPdfScene()
Вью не должна знать о том, что нужна какая-то навигация. Это не её ответственность. Имя метода лучше подбирать соответствующим образом. Вью оповещает интерактор о каком-то событии, а решение о необходимости навигации принимает интерактор.

2023-06-07 09:35 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +		view = pdfView
Переназначение ротовой вью должно быть в методе `loadView`

2023-06-07 09:44 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	}
Кажется, лучше это оставить внутри `loadView()`. Потому что обычно метод `setupUI()` вызывается из `viewDidLoad()` и это может спутать в будущем. Потом кто-то может добавить новый код внутрь этого метода не заметив, что он вызывается не из `viewDidLoad()`.

2023-06-07 09:45 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	}
Либо его можно было назвать иначе, например `setupView()`

2023-06-07 16:13 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +	}
Здесь тоже вью слишком много знает о БЛ (навигации). Метод должен просто описывать действие пользователя, например `didTapPrintBarButton()`.

2023-06-07 16:16 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +		navigationItem.setRightBarButton(barButtonItem, animated: true)
Кажется, что при появлении экрана лучше, когда кнопка будет отображаться сразу, а не будет появляться анимированно.

2023-06-08 02:21 UTC, EgorSau commented on MdEditor/Sources/Presentation/Common/Extensions/UIGraphicsPDFRendererContext+addAttributedText.swift
> +	// swiftlint:enable all
Он просит создать отдельную переменную в return и возвращать ее, а не цифру

2023-06-08 02:23 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowseHTMLFlow/BrowseHTMLCoordinator.swift
> +	}
fix

2023-06-08 02:34 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowseHTMLFlow/BrowseHTMLCoordinator.swift
> +	}
Это был копи-пейст с вашего координатора FileExplorerCoordinator. Только в этой сцене он вообще нужен - удалил.

2023-06-08 02:41 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +/// Координатор сцены просмотра pdf-файла.
У нас сцена = флоу, кроме main. Т.к. привязка к флоу идет, не вижу смысла сейчас что-то менять, т.к. сцен новых не будет в проекте. Комменты поправил.

2023-06-08 02:47 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	/// Стартует сцену с просмотром pdf-документа.
Этот метод есть только у класса коммент соответствующий.

2023-06-08 02:50 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	weak var finishDelegate: ICoordinatorFinishDelegate?
У вас так было в BrowseHTMLCoordinator и FileExplorerCoordinator :) ок, поправил

2023-06-08 02:52 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFInteractor.swift
> +	/// Получает данные для отображения на вью.
fix

2023-06-08 02:54 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFInteractor.swift
> +	// MARK: - Methods
fix

2023-06-08 02:55 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFModel.swift
> +	}
Убрал комменты

2023-06-08 02:55 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFPresenter.swift
> +	}
fix

2023-06-08 02:56 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFPresenter.swift
> +	// MARK: - Methods
fix

2023-06-08 03:03 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +// MARK: UI Setup
Поправил

2023-06-08 03:04 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +}
Поправил

2023-06-08 03:07 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +}
Одна из вариаций обозначения пустого метода или протокола. У вас как принято?

2023-06-08 03:09 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	// MARK: Lifecycle
fix

2023-06-08 03:10 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	// swiftlint:enable all
Тут принты

2023-06-08 03:11 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +	private func setupNavigation() {
setupPrintNavigationBarButton()

2023-06-08 03:12 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +// MARK: - Private methods - navigation setup
fix

2023-06-08 03:12 UTC, EgorSau commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +	func convert(text: String, pdfAuthor: String, pdfTitle: String) -> Data {
fix

2023-06-08 03:22 UTC, EgorSau commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +				cursor += 24
Добавил

2023-06-08 03:23 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFModel.swift
> +	}
Удалил

2023-06-08 03:24 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +		pdfView.pageBreakMargins = UIEdgeInsets(top: 32, left: 16, bottom: 16, right: 16)
Поправил

2023-06-08 03:25 UTC, EgorSau commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +	func convert(text: String, pdfAuthor: String, pdfTitle: String) -> Data {
fix

2023-06-08 03:25 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	}()
Добавил настройки pdfView

2023-06-08 03:31 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +		navigationItem.setRightBarButton(barButtonItem, animated: true)
Честно, думаю в нашем проекте это не принципиально :) К этому моменту требований нет.

2023-06-08 03:32 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +	}
О навигации он ничего не знает, т.к. работаем через Interactor. Название поменял.

2023-06-08 03:34 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	}
Брал за основу ваш код из других контроллеров. Тут поправил название.

2023-06-08 03:44 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneInteractor.swift
> +	func showPdfScene()
Логика тут не нарушается. Поменял название метода на printDocument().

2023-06-08 03:45 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Common/Extensions/UIGraphicsPDFRendererContext+addAttributedText.swift
> +	// swiftlint:enable all
Просто если нарушается какое-то одно правило, то и отключить лучше только его. Отключение всех правил создаёт неопределённость, не понятно, что, например, что надо поправить, чтобы правило отключать не требовалось.

А здесь если дело в магических числах, то линтер правильно ругался. Их надо поправить. Мне, допустим, не понятно вообще что это за цифры, откуда они взялись. В константах можно оставить коммент, поясняющий это.

2023-06-08 03:58 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +}
Обычно если реализация пустая, то достаточно просто пустых скобок `{}`. Чем меньше сток кода, тем лучше.
А то так, есть ощущение, что что-то хотел написать, но забыл.

2023-06-08 04:03 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +		navigationItem.setRightBarButton(barButtonItem, animated: true)
На самом деле, на важно какой проект. Обычно принято, чтобы при открытии экрана все элементы, которые можно отобразить сразу, отображались сразу. Чем меньше каких-то не обоснованных необходимостью мельканий, тем лучше.

2023-06-08 04:10 UTC, Blissfulman commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +		static let cursorSizeUpdate: CGFloat = 24
А эти две константы не связаны между собой? Они не должны быть одной и той же константой по данному контексту?

2023-06-08 04:16 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	weak var finishDelegate: ICoordinatorFinishDelegate?
Значит и там надо будет поправить

2023-06-08 04:19 UTC, Blissfulman commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	// swiftlint:enable all
Тоже лучше было бы отключить лишь одно конкретное правило. Тогда понятно что надо исправить, чтобы линтер не ругался.

2023-06-09 16:30 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +}
fix

2023-06-09 16:34 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFCoordinator.swift
> +	/// Стартует сцену с просмотром pdf-документа.
fix

2023-06-09 16:36 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/BrowsePDFFlow/BrowsePDFScene/BrowsePDFViewController.swift
> +	// swiftlint:enable all
fix

2023-06-09 18:30 UTC, EgorSau commented on MdEditor/Sources/Presentation/Flows/EditFileFlow/EditFileScene/EditFileSceneViewController.swift
> +		navigationItem.setRightBarButton(barButtonItem, animated: true)
fix

2023-06-09 18:32 UTC, EgorSau commented on MdEditor/Sources/Presentation/Common/Extensions/UIGraphicsPDFRendererContext+addAttributedText.swift
> +	// swiftlint:enable all
fix

2023-06-09 18:38 UTC, EgorSau commented on MdEditor/Sources/Services/MdToPDFConverter.swift
> +		static let cursorSizeUpdate: CGFloat = 24
Это разные по смыслу значения. Одно задает верхнюю границу, другое на каждую строку.

2023-06-09 18:42 UTC, EgorSau reviewed
Поправил все комменты

2023-06-10 11:50 UTC, Blissfulman approved these changes

2023-06-11 07:37 UTC, merged